//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmContry
    {
        public int id { get; set; }
        public int filmID { get; set; }
        public int coutryID { get; set; }
    
        public virtual Contry Contry { get; set; }
        public virtual Film Film { get; set; }
    }
}
