//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int posterID { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime actionDate { get; set; }
        public decimal price { get; set; }
        public int seatID { get; set; }
        public int collumn { get; set; }
    
        public virtual Poster Poster { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
