//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poster()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public int filmID { get; set; }
        public int hallID { get; set; }
        public decimal price { get; set; }
        public System.TimeSpan time { get; set; }
        public System.DateTime premiereDate { get; set; }
        public System.DateTime endDate { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Hall Hall { get; set; }
        public virtual Hall Hall1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
